### ISSUE TITLE
.live() is not recognized

### ISSUE THREAD

**Issue by MarceloAnzano** [PUP-CpE5-1-2016-AdvanceJava/Online_Class_Record_System_for_CE#2]
table.js line 14
$('td').live("keydown", function(e){...}

"The .live() method has been deprecated since jQuery 1.7 and has been removed in 1.9. We recommend upgrading code to use the .on() method instead." --http://jquery.com/upgrade-guide/1.9/

Dalawang jQuery kasi naka include: v2.1 at v1.11 (i.e. lab_table.php)
[Ako ba may kasalanan nito? Sorry]
Magkasundo kung ano gagamitin, sayang din kasi sa pageload.

Walang exception handling ung  mga script kaya kapag mag error ay nastop na lahat ng susunod na gagamit ng function na un. ( $(document).ready() on first script, di na magexcute $(document).ready() sa mga susunod na script)

**Comment by arian0987** [comment]
v2.1
nakita ko nga rin yan dati ginamit ko nalang ung v2.1 tpos dinelete ko yang lumang version..
isang document.ready lng kada js file pra di redundant...
kulang tayo sa time pra maglagay ng mga exceptions... console.log or alert muna gamitin...
if may issue pa comment k lng if wala na paclose na lng ng issue.
@MarceloAnzano d ko lam kung nasagot ko tanong mo e hapi bday...

**Comment by MarceloAnzano** [comment]
FYI lang, isang js file isang docu.ready pero di mageexecute ung mga docu.ready sa ibang file kapag may error agad.

Magkasundo nalang kung ano bang version gagamitin para maayos ung mga obselete na file. Check nalang natin sa final code kung may mga nadouble na js.

**Comment by arian0987** [comment]
wla namang nadobleng js saken or sa main codeigniter folder nten.. 
naencounter ko rin yang .live() issue sa table ng frontend...
'jquery-2.1.3.min' eto lng po gamitin kasi eto na ung andun sa master branch...
oks nmn sa master .. sa front end lng ata nadoble .

**Comment by arian0987** [comment]
may issue rin ata tong facebook ko ambagal mag load d makapag update T_T

**Comment by justindbms** [comment]
dun sa SAD evaluation isang .ready() lang ang pwedeng gumana; yung last na na-include na file.

**Comment by JMichaelNolasco** [comment]
Guys , since may thread na rin dito , dito na ko maglagay ng kailangan... ambagal ng facebook , di ako makaload ng page dun,,

Tasks:
*ChairPerson and Admin Tracker Page for PDF File Submission
*Archives Section (Admin, ChairPerson, Faculty)
*History Section (Faculty)
*Add Student

Final Merging
- Complete Layout/Pages for each user (faculty, admin, chair)
- Class Record Table (Lec, Lab)
- Submit Button to Confirm the End of Semester (signal to convert class record table to pdf, and turn the table into readonly)
- Freeze Pane c/o Marci . Lorenzo.Team Table

**Comment by JMichaelNolasco** [comment]
arian reminder lng ng nasa taas ^^

**Comment by JMichaelNolasco** [comment]
*** Pati yung Add Student pa pala
